// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TodoApi.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TodoApi.Pb.Messages.Todo {

  /// <summary>Holder for reflection information generated from TodoApi.proto</summary>
  public static partial class TodoApiReflection {

    #region Descriptor
    /// <summary>File descriptor for TodoApi.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TodoApiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1Ub2RvQXBpLnByb3RvEhh0b2RvYXBpLnBiLm1lc3NhZ2VzLnRvZG8aF21l",
            "c3NhZ2VzL1RvZG9JdGVtLnByb3RvGhVtZXNzYWdlcy9Db21tb24ucHJvdG8i",
            "gQEKEFRvZG9zR2V0UmVzcG9uc2USNwoGQ29tbW9uGAEgASgLMicudG9kb2Fw",
            "aS5wYi5tZXNzYWdlcy5Db21tb25EYXRhUmVzcG9uc2USNAoJVG9kb0l0ZW1z",
            "GAIgAygLMiEudG9kb2FwaS5wYi5tZXNzYWdlcy5Ub2RvSXRlbURhdGEiHAoO",
            "VG9kb0dldFJlcXVlc3QSCgoCSWQYASABKAUifwoPVG9kb0dldFJlc3BvbnNl",
            "EjcKBkNvbW1vbhgBIAEoCzInLnRvZG9hcGkucGIubWVzc2FnZXMuQ29tbW9u",
            "RGF0YVJlc3BvbnNlEjMKCFRvZG9JdGVtGAIgASgLMiEudG9kb2FwaS5wYi5t",
            "ZXNzYWdlcy5Ub2RvSXRlbURhdGFCG6oCGFRvZG9BcGkuUGIuTWVzc2FnZXMu",
            "VG9kb2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TodoApi.Pb.Messages.TodoItemReflection.Descriptor, global::TodoApi.Pb.Messages.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TodoApi.Pb.Messages.Todo.TodosGetResponse), global::TodoApi.Pb.Messages.Todo.TodosGetResponse.Parser, new[]{ "Common", "TodoItems" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TodoApi.Pb.Messages.Todo.TodoGetRequest), global::TodoApi.Pb.Messages.Todo.TodoGetRequest.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TodoApi.Pb.Messages.Todo.TodoGetResponse), global::TodoApi.Pb.Messages.Todo.TodoGetResponse.Parser, new[]{ "Common", "TodoItem" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TodosGetResponse : pb::IMessage<TodosGetResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TodosGetResponse> _parser = new pb::MessageParser<TodosGetResponse>(() => new TodosGetResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TodosGetResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TodoApi.Pb.Messages.Todo.TodoApiReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TodosGetResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TodosGetResponse(TodosGetResponse other) : this() {
      common_ = other.common_ != null ? other.common_.Clone() : null;
      todoItems_ = other.todoItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TodosGetResponse Clone() {
      return new TodosGetResponse(this);
    }

    /// <summary>Field number for the "Common" field.</summary>
    public const int CommonFieldNumber = 1;
    private global::TodoApi.Pb.Messages.CommonDataResponse common_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TodoApi.Pb.Messages.CommonDataResponse Common {
      get { return common_; }
      set {
        common_ = value;
      }
    }

    /// <summary>Field number for the "TodoItems" field.</summary>
    public const int TodoItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::TodoApi.Pb.Messages.TodoItemData> _repeated_todoItems_codec
        = pb::FieldCodec.ForMessage(18, global::TodoApi.Pb.Messages.TodoItemData.Parser);
    private readonly pbc::RepeatedField<global::TodoApi.Pb.Messages.TodoItemData> todoItems_ = new pbc::RepeatedField<global::TodoApi.Pb.Messages.TodoItemData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::TodoApi.Pb.Messages.TodoItemData> TodoItems {
      get { return todoItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TodosGetResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TodosGetResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Common, other.Common)) return false;
      if(!todoItems_.Equals(other.todoItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (common_ != null) hash ^= Common.GetHashCode();
      hash ^= todoItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (common_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Common);
      }
      todoItems_.WriteTo(output, _repeated_todoItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (common_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Common);
      }
      todoItems_.WriteTo(ref output, _repeated_todoItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (common_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Common);
      }
      size += todoItems_.CalculateSize(_repeated_todoItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TodosGetResponse other) {
      if (other == null) {
        return;
      }
      if (other.common_ != null) {
        if (common_ == null) {
          Common = new global::TodoApi.Pb.Messages.CommonDataResponse();
        }
        Common.MergeFrom(other.Common);
      }
      todoItems_.Add(other.todoItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (common_ == null) {
              Common = new global::TodoApi.Pb.Messages.CommonDataResponse();
            }
            input.ReadMessage(Common);
            break;
          }
          case 18: {
            todoItems_.AddEntriesFrom(input, _repeated_todoItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (common_ == null) {
              Common = new global::TodoApi.Pb.Messages.CommonDataResponse();
            }
            input.ReadMessage(Common);
            break;
          }
          case 18: {
            todoItems_.AddEntriesFrom(ref input, _repeated_todoItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TodoGetRequest : pb::IMessage<TodoGetRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TodoGetRequest> _parser = new pb::MessageParser<TodoGetRequest>(() => new TodoGetRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TodoGetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TodoApi.Pb.Messages.Todo.TodoApiReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TodoGetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TodoGetRequest(TodoGetRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TodoGetRequest Clone() {
      return new TodoGetRequest(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TodoGetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TodoGetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TodoGetRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TodoGetResponse : pb::IMessage<TodoGetResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TodoGetResponse> _parser = new pb::MessageParser<TodoGetResponse>(() => new TodoGetResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TodoGetResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TodoApi.Pb.Messages.Todo.TodoApiReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TodoGetResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TodoGetResponse(TodoGetResponse other) : this() {
      common_ = other.common_ != null ? other.common_.Clone() : null;
      todoItem_ = other.todoItem_ != null ? other.todoItem_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TodoGetResponse Clone() {
      return new TodoGetResponse(this);
    }

    /// <summary>Field number for the "Common" field.</summary>
    public const int CommonFieldNumber = 1;
    private global::TodoApi.Pb.Messages.CommonDataResponse common_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TodoApi.Pb.Messages.CommonDataResponse Common {
      get { return common_; }
      set {
        common_ = value;
      }
    }

    /// <summary>Field number for the "TodoItem" field.</summary>
    public const int TodoItemFieldNumber = 2;
    private global::TodoApi.Pb.Messages.TodoItemData todoItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TodoApi.Pb.Messages.TodoItemData TodoItem {
      get { return todoItem_; }
      set {
        todoItem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TodoGetResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TodoGetResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Common, other.Common)) return false;
      if (!object.Equals(TodoItem, other.TodoItem)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (common_ != null) hash ^= Common.GetHashCode();
      if (todoItem_ != null) hash ^= TodoItem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (common_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Common);
      }
      if (todoItem_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TodoItem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (common_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Common);
      }
      if (todoItem_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TodoItem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (common_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Common);
      }
      if (todoItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TodoItem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TodoGetResponse other) {
      if (other == null) {
        return;
      }
      if (other.common_ != null) {
        if (common_ == null) {
          Common = new global::TodoApi.Pb.Messages.CommonDataResponse();
        }
        Common.MergeFrom(other.Common);
      }
      if (other.todoItem_ != null) {
        if (todoItem_ == null) {
          TodoItem = new global::TodoApi.Pb.Messages.TodoItemData();
        }
        TodoItem.MergeFrom(other.TodoItem);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (common_ == null) {
              Common = new global::TodoApi.Pb.Messages.CommonDataResponse();
            }
            input.ReadMessage(Common);
            break;
          }
          case 18: {
            if (todoItem_ == null) {
              TodoItem = new global::TodoApi.Pb.Messages.TodoItemData();
            }
            input.ReadMessage(TodoItem);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (common_ == null) {
              Common = new global::TodoApi.Pb.Messages.CommonDataResponse();
            }
            input.ReadMessage(Common);
            break;
          }
          case 18: {
            if (todoItem_ == null) {
              TodoItem = new global::TodoApi.Pb.Messages.TodoItemData();
            }
            input.ReadMessage(TodoItem);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
